AllCops:
  TargetRubyVersion: 1.9

Style/Alias:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'jbuilder-jpartial.gemspec'
    - 'spec/**/*'
    - 'Rakefile'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
